export const countries = [
  { country: "Afghanistan", code: "AF" },
  { country: "Albania", code: "AL" },
  { country: "Algeria", code: "DZ" },
  { country: "American Samoa", code: "AS" },
  { country: "Andorra", code: "AD" },
  { country: "Angola", code: "AO" },
  { country: "Anguilla", code: "AI" },
  { country: "Antigua", code: "AG" },
  { country: "Argentina", code: "AR" },
  { country: "Armenia", code: "AM" },
  { country: "Aruba", code: "AW" },
  { country: "Australia", code: "AU" },
  { country: "Austria", code: "AT" },
  { country: "Azerbaijan", code: "AZ" },
  { country: "Bahamas", code: "BS" },
  { country: "Bahrain", code: "BH" },
  { country: "Bangladesh", code: "BD" },
  { country: "Barbados", code: "BB" },
  { country: "Belarus", code: "BY" },
  { country: "Belgium", code: "BE" },
  { country: "Belize", code: "BZ" },
  { country: "Benin", code: "BJ" },
  { country: "Bermuda", code: "BM" },
  { country: "Bhutan", code: "BT" },
  { country: "Bolivia", code: "BO" },
  { country: "Bonaire", code: "XB" },
  { country: "Bosnia & Herzegovina", code: "BA" },
  { country: "Botswana", code: "BW" },
  { country: "Brazil", code: "BR" },
  { country: "Brunei", code: "BN" },
  { country: "Bulgaria", code: "BG" },
  { country: "Burkina Faso", code: "BF" },
  { country: "Burundi", code: "BI" },
  { country: "Cambodia", code: "KH" },
  { country: "Cameroon", code: "CM" },
  { country: "Canada", code: "CA" },
  { country: "Canary Islands", code: "IC" },
  { country: "Cape Verde", code: "CV" },
  { country: "Cayman Islands", code: "KY" },
  { country: "Central African Rep", code: "CF" },
  { country: "Chad", code: "TD" },
  { country: "Chile", code: "CL" },
  { country: "China", code: "CN" },
  { country: "Colombia", code: "CO" },
  { country: "Comoros", code: "KM" },
  { country: "Congo", code: "CG" },
  { country: "Congo, DPR", code: "CD" },
  { country: "Cook Islands", code: "CK" },
  { country: "Costa Rica", code: "CR" },
  { country: "Cote D Ivoire", code: "CI" },
  { country: "Croatia", code: "HR" },
  { country: "Cuba", code: "CU" },
  { country: "Curacao", code: "XC" },
  { country: "Cyprus", code: "CY" },
  { country: "Czech Rep., The", code: "CZ" },
  { country: "Denmark", code: "DK" },
  { country: "Djibouti", code: "DJ" },
  { country: "Dominica", code: "DM" },
  { country: "Dominican Rep.", code: "DO" },
  { country: "Ecuador", code: "EC" },
  { country: "Egypt", code: "EG" },
  { country: "El Salvador", code: "SV" },
  { country: "Eritrea", code: "ER" },
  { country: "Estonia", code: "EE" },
  { country: "Eswatini", code: "SZ" },
  { country: "Ethiopia", code: "ET" },
  { country: "Falkland Islands", code: "FK" },
  { country: "Faroe Islands", code: "FO" },
  { country: "Fiji", code: "FJ" },
  { country: "Finland", code: "FI" },
  { country: "France", code: "FR" },
  { country: "French Guyana", code: "GF" },
  { country: "Gabon", code: "GA" },
  { country: "Gambia", code: "GM" },
  { country: "Georgia", code: "GE" },
  { country: "Germany", code: "DE" },
  { country: "Ghana", code: "GH" },
  { country: "Gibraltar", code: "GI" },
  { country: "Greece", code: "GR" },
  { country: "Greenland", code: "GL" },
  { country: "Grenada", code: "GD" },
  { country: "Guadeloupe", code: "GP" },
  { country: "Guam", code: "GU" },
  { country: "Guatemala", code: "GT" },
  { country: "Guernsey", code: "GG" },
  { country: "Guinea Rep.", code: "GN" },
  { country: "Guinea-Bissau", code: "GW" },
  { country: "Guinea-Equatorial", code: "GQ" },
  { country: "Guyana (British)", code: "GY" },
  { country: "Haiti", code: "HT" },
  { country: "Honduras", code: "HN" },
  { country: "Hong Kong SAR China", code: "HK" },
  { country: "Hungary", code: "HU" },
  { country: "Iceland", code: "IS" },
  { country: "India", code: "IN" },
  { country: "Indonesia", code: "ID" },
  { country: "Iran", code: "IR" },
  { country: "Iraq", code: "IQ" },
  { country: "Ireland, Rep. Of", code: "IE" },
  { country: "Italy", code: "IT" },
  { country: "Jamaica", code: "JM" },
  { country: "Japan", code: "JP" },
  { country: "Jersey", code: "JE" },
  { country: "Jordan", code: "JO" },
  { country: "Kazakhstan", code: "KZ" },
  { country: "Kenya", code: "KE" },
  { country: "Kiribati", code: "KI" },
  { country: "Korea, Rep. Of", code: "KR" },
  { country: "Korea,  D.P.R Of", code: "KP" },
  { country: "Kosovo", code: "KV" },
  { country: "Kuwait", code: "KW" },
  { country: "Kyrgyzstan", code: "KG" },
  { country: "Laos", code: "LA" },
  { country: "Latvia", code: "LV" },
  { country: "Lebanon", code: "LB" },
  { country: "Lesotho", code: "LS" },
  { country: "Liberia", code: "LR" },
  { country: "Libya", code: "LY" },
  { country: "Liechtenstein", code: "LI" },
  { country: "Lithuania", code: "LT" },
  { country: "Luxembourg", code: "LU" },
  { country: "Macau SAR China", code: "MO" },
  { country: "Madagascar", code: "MG" },
  { country: "Malawi", code: "MW" },
  { country: "Malaysia", code: "MY" },
  { country: "Maldives", code: "MV" },
  { country: "Mali", code: "ML" },
  { country: "Malta", code: "MT" },
  { country: "Mariana Islands", code: "MP" },
  { country: "Marshall Islands", code: "MH" },
  { country: "Martinique", code: "MQ" },
  { country: "Mauritania", code: "MR" },
  { country: "Mauritius", code: "MU" },
  { country: "Mayotte", code: "YT" },
  { country: "Mexico", code: "MX" },
  { country: "Micronesia", code: "FM" },
  { country: "Moldova, Rep. Of", code: "MD" },
  { country: "Monaco", code: "MC" },
  { country: "Mongolia", code: "MN" },
  { country: "Montenegro, Rep Of", code: "ME" },
  { country: "Montserrat", code: "MS" },
  { country: "Morocco", code: "MA" },
  { country: "Mozambique", code: "MZ" },
  { country: "Myanmar", code: "MM" },
  { country: "Namibia", code: "NA" },
  { country: "Nauru, Rep. Of", code: "NR" },
  { country: "Nepal", code: "NP" },
  { country: "Netherlands, The", code: "NL" },
  { country: "Nevis", code: "XN" },
  { country: "New Caledonia", code: "NC" },
  { country: "New Zealand", code: "NZ" },
  { country: "Nicaragua", code: "NI" },
  { country: "Niger", code: "NE" },
  { country: "Nigeria", code: "NG" },
  { country: "Niue", code: "NU" },
  { country: "North Macedonia", code: "MK" },
  { country: "Norway", code: "NO" },
  { country: "Oman", code: "OM" },
  { country: "Pakistan", code: "PK" },
  { country: "Palau", code: "PW" },
  { country: "Panama", code: "PA" },
  { country: "Papua New Guinea", code: "PG" },
  { country: "Paraguay", code: "PY" },
  { country: "Peru", code: "PE" },
  { country: "Philippines, The", code: "PH" },
  { country: "Poland", code: "PL" },
  { country: "Portugal", code: "PT" },
  { country: "Puerto Rico", code: "PR" },
  { country: "Qatar", code: "QA" },
  { country: "Reunion, Island Of", code: "RE" },
  { country: "Romania", code: "RO" },
  { country: "Russian Federation", code: "RU" },
  { country: "Rwanda", code: "RW" },
  { country: "Saint Helena", code: "SH" },
  { country: "Saint Lucia", code: "LC" },
  { country: "Saint Vincent", code: "VC" },
  { country: "Samoa", code: "WS" },
  { country: "San Marino", code: "SM" },
  { country: "Sao Tome And Principe", code: "ST" },
  { country: "Saudi Arabia", code: "SA" },
  { country: "Senegal", code: "SN" },
  { country: "Serbia, Rep. Of", code: "RS" },
  { country: "Seychelles", code: "SC" },
  { country: "Sierra Leone", code: "SL" },
  { country: "Singapore", code: "SG" },
  { country: "Slovakia", code: "SK" },
  { country: "Slovenia", code: "SI" },
  { country: "Solomon Islands", code: "SB" },
  { country: "Somalia", code: "SO" },
  { country: "Somaliland, Rep Of", code: "XS" },
  { country: "South Africa", code: "ZA" },
  { country: "South Sudan", code: "SS" },
  { country: "Spain", code: "ES" },
  { country: "Sri Lanka", code: "LK" },
  { country: "St. Barthelemy", code: "XY" },
  { country: "St. Eustatius", code: "XE" },
  { country: "St. Kitts", code: "KN" },
  { country: "St. Maarten", code: "XM" },
  { country: "Sudan", code: "SD" },
  { country: "Suriname", code: "SR" },
  { country: "Sweden", code: "SE" },
  { country: "Switzerland", code: "CH" },
  { country: "Syria", code: "SY" },
  { country: "Tahiti", code: "PF" },
  { country: "Taiwan", code: "TW" },
  { country: "Tajikistan", code: "TJ" },
  { country: "Tanzania", code: "TZ" },
  { country: "Thailand", code: "TH" },
  { country: "Timor-Leste", code: "TL" },
  { country: "Togo", code: "TG" },
  { country: "Tonga", code: "TO" },
  { country: "Trinidad And Tobago", code: "TT" },
  { country: "Tunisia", code: "TN" },
  { country: "Turkey", code: "TR" },
  { country: "Turkmenistan", code: "TM" },
  { country: "Turks & Caicos", code: "TC" },
  { country: "Tuvalu", code: "TV" },
  { country: "USA", code: "US" },
  { country: "Uganda", code: "UG" },
  { country: "Ukraine", code: "UA" },
  { country: "United Arab Emirates", code: "AE" },
  { country: "United Kingdom", code: "GB" },
  { country: "Uruguay", code: "UY" },
  { country: "Uzbekistan", code: "UZ" },
  { country: "Vanuatu", code: "VU" },
  { country: "Vatican City", code: "VA" },
  { country: "Venezuela", code: "VE" },
  { country: "Vietnam", code: "VN" },
  { country: "Virgin Islands-British", code: "VG" },
  { country: "Virgin Islands-US", code: "VI" },
  { country: "Yemen, Rep. Of", code: "YE" },
  { country: "Zambia", code: "ZM" },
  { country: "Zimbabwe", code: "ZW" },
];
